# Generated by Django 4.2.1 on 2023-06-01 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 2, 17, 57, 803729, tzinfo=datetime.timezone.utc)),
        ),
    ]
